# Generated by Django 6.0.2 on 2026-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default='14:00', verbose_name='Check-in Time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(default='12:00', verbose_name='Check-out Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Check-in Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='Check-out Date'),
        ),
    ]
