# Generated by Django 6.0.2 on 2026-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('booking', 'Booking'), ('payment', 'Payment'), ('checkout', 'Checkout'), ('review', 'Review'), ('offer', 'Hotel Offer'), ('room_offer', 'Room Offer'), ('special_deal', 'Special Deal'), ('announcement', 'Hotel Announcement')], default='general', max_length=50),
        ),
    ]
